Use group/version/kind instead of kind
kappnav/apis pull request #33
Opened 2019-12-07 19:01 UTC by paulben

2019-12-11 17:00 UTC, mrglavas requested changes
Found one issue and made a suggestion on something else.

2019-12-11 17:00 UTC, mrglavas commented on src/main/java/application/rest/v1/ComponentsEndpoint.java
> +                    String group = null;
Something looks wrong here. group either equals null or empty string. Didn't you mean to set it to ComponentKind.group and then replace "core" with empty string? Probably better to put that logic in ComponentKind so that its used consistently.

2019-12-11 17:00 UTC, mrglavas commented on src/main/java/application/rest/v1/ComponentsEndpoint.java
> +                    Map<String, String> groupKindMap = registry.groupKindToApiVersionMap.get();
Suggestion: Lines 109-116 feel like they should be a method on ComponentInfoRegistry that returns the apiVersion for a ComponentKind.

2019-12-11 17:10 UTC, mrglavas commented on src/main/java/application/rest/v1/ComponentsEndpoint.java
> +                    Map<String, String> groupKindMap = registry.groupKindToApiVersionMap.get();
or even have listClusterObject() and listNamespacedObject() methods that take ComponentKind as a parameter and have those methods contain this logic.

2019-12-12 15:24 UTC, paulben commented on src/main/java/application/rest/v1/ComponentsEndpoint.java
> +                    String group = null;
@mrglavas I fixed that, and moved the logic to a new method in ComponentInfoRegistry as you suggested.

2019-12-12 15:24 UTC, paulben commented on src/main/java/application/rest/v1/ComponentsEndpoint.java
> +                    Map<String, String> groupKindMap = registry.groupKindToApiVersionMap.get();
@mrglavas I fixed that, and moved the logic to a new method in ComponentInfoRegistry as you suggested.

2019-12-12 16:46 UTC, mrglavas approved these changes

2019-12-12 16:47 UTC, merged