fix: Use user from cookie to list of commands
kappnav/apis pull request #49
Opened 2020-01-23 15:42 UTC by kinueng

Related to kappnav/issues#81
- Get the username from the OpenShift oauth-proxy cookie

- Add more logging

2020-01-24 16:42 UTC, juniartisu requested changes
Kin, looks good but can you also add an EXIT since you added an ENTRY. Otherwise you can change the ENTRY to DEBUG instead. BTW thanks for adding more logging as needed.
Thanks.

2020-01-24 16:44 UTC, kinueng commented
Good catch, I'll add the exit log

2020-01-24 19:57 UTC, kinueng commented
I rebuilt and retested the new 4d25c92 using the two `curl` commands in the issue description.  Ready for you to review again, @juniartisu

2020-01-27 13:04 UTC, juniartisu approved these changes

2020-01-27 13:04 UTC, merged