Issue#104: add custom resource watcher to monitor logging configuration
kappnav/apis pull request #52
Opened 2020-01-30 15:59 UTC by amylin1

for issue#104

2020-01-30 19:00 UTC, mrglavas requested changes

2020-01-30 19:00 UTC, mrglavas commented on src/main/java/com/ibm/kappnav/logging/Logger.java
> +                            if (name.equals("kappnav")) {
The name of the CR could be anything. You shouldn't hard code this. The CR name is passed in as an environment variable to the container. You should use the value of the environment variable "KAPPNAV_CR_NAME" to look up the CR. You also have the namespace "KAPPNAV_CONFIG_NAMESPACE".

2020-01-30 19:00 UTC, mrglavas commented on src/main/java/com/ibm/kappnav/logging/Logger.java
> +            Object cr = coa.listClusterCustomObject(KAPPNAV_CR_GROUP, KAPPNAV_CR_VERSION, KAPPNAV_CR_PLURAL, null, null, null, null);
You can query for the specific CR you're looking for. You don't need the whole list of everything in the cluster.

2020-01-30 19:00 UTC, mrglavas commented on src/main/java/application/rest/v1/CustomResourceWatcher.java
> +                                    coa.listClusterCustomObjectCall(KAPPNAV_CR_GROUP, KAPPNAV_CR_VERSION, KAPPNAV_CR_PLURAL, null, null, null, Boolean.TRUE, null, null),
You should probably set your watch on the kAppNav namespace so you're not watching the entire cluster.

2020-01-30 19:00 UTC, mrglavas commented on src/main/java/application/rest/v1/CustomResourceWatcher.java
> +                                    //only handle ADDED case
Didn't you really mean to handle both the ADDED and MODIFIED events? The purpose of the watch is for monitoring for changes.

2020-01-30 19:00 UTC, mrglavas commented on src/main/java/com/ibm/kappnav/logging/Logger.java
> +                CustomResourceWatcher.startCustomResourceWatcher();
As you currently have this coded, if the watch stops for some reason, it will not be restarted. The thread will wait forever and no changes to the CR will ever be picked up.

2020-01-30 19:00 UTC, mrglavas commented on src/main/java/application/rest/v1/CustomResourceWatcher.java
> +        if (name.equals("kappnav")) {
The CR name can be anything. You shouldn't hard code this. See my other comment about this for more details.

2020-01-31 17:13 UTC, mrglavas approved these changes

2020-01-31 19:27 UTC, amylin1 commented
I tested on ocp 4.3 and it also works fine.

2020-01-31 19:30 UTC, merged

2020-02-04 14:58 UTC, rlcundiff commented
For https://github.com/kappnav/issues/issues/104